/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type { IECRegistry, IECRegistryInterface } from "../IECRegistry";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
      {
        internalType: "uint16",
        name: "",
        type: "uint16",
      },
    ],
    name: "addressCanModifyTrait",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
      {
        internalType: "uint16[]",
        name: "",
        type: "uint16[]",
      },
    ],
    name: "addressCanModifyTraits",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint16",
        name: "traitID",
        type: "uint16",
      },
    ],
    name: "getImplementer",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint16",
        name: "traitID",
        type: "uint16",
      },
      {
        internalType: "uint16",
        name: "tokenID",
        type: "uint16",
      },
    ],
    name: "hasTrait",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint16",
        name: "traitID",
        type: "uint16",
      },
      {
        internalType: "uint16",
        name: "tokenID",
        type: "uint16",
      },
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    name: "setTrait",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class IECRegistry__factory {
  static readonly abi = _abi;
  static createInterface(): IECRegistryInterface {
    return new utils.Interface(_abi) as IECRegistryInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IECRegistry {
    return new Contract(address, _abi, signerOrProvider) as IECRegistry;
  }
}
