/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type {
  TraitUint8ValueImplementer,
  TraitUint8ValueImplementerInterface,
} from "../TraitUint8ValueImplementer";

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "uint16",
        name: "_tokenId",
        type: "uint16",
      },
      {
        indexed: false,
        internalType: "uint8",
        name: "_newData",
        type: "uint8",
      },
    ],
    name: "updateTraitEvent",
    type: "event",
  },
  {
    inputs: [],
    name: "ECRegistry",
    outputs: [
      {
        internalType: "contract IECRegistry",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint16",
        name: "_tokenId",
        type: "uint16",
      },
    ],
    name: "getValue",
    outputs: [
      {
        internalType: "uint8",
        name: "",
        type: "uint8",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "implementerType",
    outputs: [
      {
        internalType: "uint8",
        name: "",
        type: "uint8",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint16[]",
        name: "_tokenIds",
        type: "uint16[]",
      },
      {
        internalType: "uint8[]",
        name: "_value",
        type: "uint8[]",
      },
    ],
    name: "setData",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint16[]",
        name: "_tokenIds",
        type: "uint16[]",
      },
      {
        internalType: "uint8[]",
        name: "_value",
        type: "uint8[]",
      },
    ],
    name: "setDataNoEvent",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint16",
        name: "_tokenId",
        type: "uint16",
      },
      {
        internalType: "uint8",
        name: "_value",
        type: "uint8",
      },
    ],
    name: "setValue",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "traitId",
    outputs: [
      {
        internalType: "uint16",
        name: "",
        type: "uint16",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

export class TraitUint8ValueImplementer__factory {
  static readonly abi = _abi;
  static createInterface(): TraitUint8ValueImplementerInterface {
    return new utils.Interface(_abi) as TraitUint8ValueImplementerInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): TraitUint8ValueImplementer {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as TraitUint8ValueImplementer;
  }
}
